//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hizmet_noktalari
    {
        public int id { get; set; }
        public string Format_Ad { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Magaza_Ad { get; set; }
        public string kurulum_tarihi { get; set; }
        public string Marka_Ad { get; set; }
        public Nullable<int> Kapali_Alan { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public string Adres { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        public virtual iletisim_bilgileri iletisim_bilgileri { get; set; }
    }
}
