//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim_bilgileri
    {
        public int Magaza_No { get; set; }
        public string Magaza_Ad { get; set; }
        public string Sube { get; set; }
        public string Marka_Ad { get; set; }
        public string Format_Ad { get; set; }
        public string Durum { get; set; }
        public string Acilis_Tarihi { get; set; }
        public string Sezonluk { get; set; }
        public Nullable<decimal> Telefon1 { get; set; }
        public string Standart_Adres { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    
        public virtual hizmet_noktalari hizmet_noktalari { get; set; }
        public virtual iletisim_bilgileri iletisim_bilgileri1 { get; set; }
        public virtual iletisim_bilgileri iletisim_bilgileri2 { get; set; }
    }
}
