//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCity_District_Street_Town
    {
        public int id { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string semt_bucak_belde { get; set; }
        public string mahalle { get; set; }
        public string posta_kodu { get; set; }
    }
}
