//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_il_ilce_latlng
    {
        public int id { get; set; }
        public string sehir { get; set; }
        public string sehir_alt { get; set; }
        public string semt { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    }
}
